version: "3.7"
services:
  app:
    image: node:16-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
       - 5050:5050
    working_dir: /app
    volumes:
       - ./:/app
    environment:
       MYSQL_HOST: mysql
       MYSQL_USER: root
       MYSQL_PASSWORD: secret
       MYSQL_DB: node-ts-boilerplate-db
  mysql:
     image: mysql:5.7
     volumes:
       - node-ts-boilerplate-data:/var/lib/mysql
volumes:
   node-ts-boilerplate-data:
