name: Build and Release
on:
  push:
    branches: [main, docker_ci_cd ] 
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get release tag
        id: get_version
        uses: battila7/get-version-action@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/node-ts-boilerplate:latest
          # tags: |
          #   docker.pkg.github.com/${{ github.repository }}/node-ts-boilerplate:latest
          #   docker.pkg.github.com/${{ github.repository }}/node-ts-boilerplate:${{ steps.get_version.outputs.version-without-v }}
          #   rsbh/node-ts-boilerplate:latest
          #   rsbh/node-ts-boilerplate:${{ steps.get_version.outputs.version-without-v }}
